### ISSUE TITLE
show_between_R2 not working with LinearModels

### ISSUE THREAD

**Issue by SwannChelly** [StatsReporting/stargazer#108]
I all, when using: 

reg = PanelOLS.from_formula(formula,other_effects=tmp['additional_FE'], data=tmp,drop_absorbed=True).fit())
stg = Stargazer(stg)
stg.show_within_r2 = True

the within R2 is not added in the regression table. 

Also could it be able to have a "show_between_r2"  method please ? 

Thank you for your investment !

Best, 
SC

**Comment by toobaz** [comment]
> stg = Stargazer(stg)

I'm afraid this line doesn't make much sense.

Anyway, within R2 seems to work, as also featured in the examples (see the first after "**Display panel results from linearmodels**"): https://github.com/StatsReporting/stargazer/blob/master/examples.ipynb

It seems like `show_between_R2`, which is already included in the `linearmodel` translator, is not working instead ( @dsliwka did it work for you?).

Renaming issue accordingly.

**Comment by SwannChelly** [comment]
Thank you, 

Another point is that PanelOLS has "rsquared_inclusive" which is the same than the R-squared displayed in Stata reghdfe table. Looking into the source code, this "rsquared_inclusive" is being computed including all the fixed effect. I feel it could be of use to also have an option to display it. 

Best, 
SC

**Comment by toobaz** [comment]
> It seems like `show_between_R2`, which is already included in the `linearmodel` translator, is not working instead

Well, it couldn't possibly work, as it was recognized by the `linearmodel` translator but entirely unknown to `stargazer.Stargazer`. Fixed now.

Concerning the other request, I opened the more general #109 .
