### ISSUE TITLE
Pseudo R-squared for Logit

### ISSUE THREAD

**Issue by samemon** [StatsReporting/stargazer#91]
When printing the summary for logit, Pseudo R-Squared isn't printed. Is there support for that?

**Comment by abuabara** [comment]
it would be interesting to be able to include r-squared (pseudo) for all glm. I can do that in one model, using `add.lines = list(c("R2", paste(as.character(round(data.frame(performance::r2(mod1))[1,1], digits = 4)))))` but this is ideal, especially if you have a comparison of several models in the output, it doesn't work well.

**Comment by toobaz** [comment]
@samemon fixed in master

@abuabara are you sure you are in the right place? This project is the _Python_ version of stargazer.
