### ISSUE TITLE
Is it possible to use statsmodels time series models with this package ?

### ISSUE THREAD

**Issue by elemn** [StatsReporting/stargazer#96]
Hello,

I am attempting to export the results of an ARDL model I calculated with statsmodels, but I get the impression that the package only supports OLS (no ARDL, ARIMA). Is there a makeshift way to get this working? Right now, running : 

> Stargazer([model_fit])

returns "ValueError: Please use trained OLS models as inputs".

The actual model output should be very similar to OLS.

**Comment by toobaz** [comment]
Hi @elemn . While the message of the ValueError is definitely misleading, it seems to me that stargazer supports ARDL just fine. At least, the following code, combining and ARDL and an OLS, doesn't raise any error for me, and outputs a table (in jupyter):

```python3
from statsmodels.tsa.api import ARDL
from statsmodels.datasets import danish_data
data = danish_data.load_pandas().data
lrm = data.lrm
exog = data[["lry", "ibo", "ide"]]
m = ARDL(data.lrm, 3, data[["lry", "ibo", "ide"]], 3).fit()

from sklearn import datasets
import pandas as pd
import statsmodels.api as sm

diabetes = datasets.load_diabetes()
df = pd.DataFrame(diabetes.data)
df.columns = ['Age', 'Sex', 'BMI', 'ABP', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6']
df['target'] = diabetes.target

est = sm.OLS(endog=df['target'], exog=sm.add_constant(df[df.columns[0:4]])).fit()

from stargazer.stargazer import Stargazer
table = Stargazer([m, est])
table
```

**Comment by toobaz** [comment]
Sorry, I should have mentioned that the above works with current master. I confirm that the error you report does rise with the last version on pypi, 0.0.5.

I will upload a new version, hopefully before the end of July.

**Comment by elemn** [comment]
Hello @toobaz , thank you very much for your response! If possible, would you be able to post back here once that master is uploaded? It would very much be appreciated.

**Comment by toobaz** [comment]
Hello @elemn , stargazer 0.0.6 was just uploaded to pypi!

**Comment by toobaz** [comment]
Hello @elemn , stargazer 0.0.6 was just uploaded to pypi!

**Comment by alistaircameron** [comment]
Hello,

I am having the same issue as the OP, but with PanelOLS from linearmodels. Specifically, updating linearmodels and stargazer to the current versions, then running the PanelOLS example in examples.ipynb from stargazer's documentation returns "ValueError: Please use trained OLS models as inputs". 

Many thanks for your work, it's a great package!

**Comment by toobaz** [comment]
> I am having the same issue as the OP, but with PanelOLS from linearmodels

Hi @alistaircameron , see https://github.com/StatsReporting/stargazer/pull/98 : support PanelOLS was just merged and will be included in next release, I guess in the next month or so. If you are in a hurry, you can use the git version for now.
