### ISSUE TITLE
cannot see output in Pycharm 

### ISSUE THREAD

**Issue by msh855** [StatsReporting/stargazer#97]
Hi, 
I am using the examples in of the package and I cannot see the HTML output

**Comment by toobaz** [comment]
Jupyter has a [simple way](https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display) to integrate arbitrary html output... no idea about Pycharm. Please reopen if you can provide detailed info, as I don't know the software (and a quick online search didn't help).

**Comment by msh855** [comment]
I have found this solution as a work around: 

```

tables = Stargazer(models)
tables.covariate_order(x_fixed + x_to_try + ['const'])
reg_table = tables.render_html()

with open("reg_table.html", "w") as file:
    file.write(reg_table)

```

**Comment by toobaz** [comment]
> I have found this solution as a work around:

Sorry, not clear in which sense this is a work around. When you do the above, (how) will the HTML output then show up in the pycharm window?

**Comment by msh855** [comment]
Does not open a window.  I think in Pycharm is not possible (until now I couldn't find something that worked in relation to this)

The code It just exports the results as an html file. So, something, better than nothing.
